// CupVerdict copy in Spanish, Polish and Swedish: only what is specific to the site (quiz,
// calculators, home); the generic interface comes from the engine (src/i18n/ui.ts).
const names = (a: string, b: string, c: string, d: string) => ({
  'tool-brew-ratio': a,
  'tool-home-payback': b,
  'tool-cafe-cost': c,
  'tool-office-cost': d,
});

export const es = {
  tagline: 'Decisiones de café, con datos.',
  nav: { find: 'Encuentra tu cafetera' },
  quiz: {
    title: '¿Qué cafetera es para ti?',
    sub: '3 preguntas rápidas: CupVerdict te dice cuál comprar, y por qué.',
    q1: '¿Cómo tomas el café?',
    a1: { espresso: 'Espresso', milk: 'Capuchino y con leche', moka: 'Cafetera italiana', filter: 'Largo / de filtro' },
    q2: '¿Cuánto esfuerzo?',
    a2: { button: 'Pulsar un botón', ritual: 'Disfruto el ritual' },
    q3: '¿Tu presupuesto?',
  },
  verdict: {
    indexDescription: 'Una elección clara por tipo de cafetera, basada en las especificaciones publicadas por los fabricantes.',
    findMachine: 'Encuentra la cafetera que te va',
    calc: '¿Cuánto ahorras frente al café de la cafetería?',
    budgetNote: 'Ninguna cafetera de este tipo que recomendamos encaja exactamente en tu presupuesto: esta es la más cercana.',
  },
  footer: { line: 'Primero los datos. Luego las opiniones.' },
  about: {
    what: 'cafeteras de cápsulas, superautomáticas, italianas y de goteo, filtros manuales, prensas francesas y molinillos',
    description: 'Sobre nosotros: CupVerdict es un sitio independiente que te ayuda a elegir cafetera, cafetera italiana o molinillo. Cómo elegimos y cómo ganamos dinero.',
  },
  home: {
    metaDescription: 'Calculadoras de café gratuitas y guías basadas en datos para casa, oficina y cafetería. Cada dato de producto enlaza a su fuente.',
    pickDirect: 'O elige directamente un tipo',
    toolsStrip: 'Calculadoras útiles: cuánto te cuesta de verdad el café y cuánto te ahorra una cafetera.',
    allTools: 'Todas las calculadoras',
    seo: {
      keyphrase: 'CupVerdict',
      title: 'CupVerdict: qué cafetera o molinillo de café comprar',
      description: 'CupVerdict te ayuda a elegir cafetera de cápsulas, superautomática, italiana o de goteo, filtro manual o molinillo: 3 preguntas, un modelo, con fuentes.',
    },
    how: {
      title: 'Cómo elige CupVerdict',
      image: 'Dibujo de CupVerdict: cafetera de cápsulas, máquina de espresso, cafetera italiana y molinillo de café',
      points: [
        {
          t: 'Empiezas por cómo tomas el café',
          d: 'Dinos cómo tomas el café y cuánto esfuerzo quieres hacer: primero la cafetera que te va, con el motivo en palabras sencillas; debajo, todos los modelos a la venta en tu país, para ordenarlos como quieras.',
        },
        {
          t: 'Cada número tiene su fuente',
          d: 'Presión, capacidad y medidas salen de las páginas oficiales de los fabricantes y de las pruebas independientes. Junto a cada dato hay un enlace para comprobarlo tú.',
        },
        {
          t: 'Ninguna marca paga por salir elegida',
          d: 'Si compras desde un enlace nuestro podemos recibir una comisión, sin coste para ti. Nunca cambia la elección, y ninguna marca ve nuestras páginas antes de publicarlas.',
        },
      ],
      tests: 'Pruebas independientes que citamos:',
      more: 'Cómo trabaja CupVerdict, en detalle',
    },
    faq: [
      {
        q: '¿Cápsulas o superautomática: qué sale más barato por taza?',
        a: 'Por taza, el café en grano cuesta menos que las cápsulas; la superautomática, en cambio, cuesta más al comprarla. Cuanto más café tomas, antes se recupera la diferencia.',
        cat: 'superautomatic',
      },
      {
        q: '¿Cafetera italiana o máquina de espresso?',
        a: 'La cafetera italiana hace un café fuerte en el fuego por poco dinero, pero no un espresso de verdad: extrae con mucha menos presión. Para un espresso con crema hace falta una máquina de espresso.',
        cat: 'moka',
      },
      {
        q: '¿Necesito un molinillo de café?',
        a: 'Solo si compras café en grano: molido justo antes conserva más aroma. Para espresso el molinillo debe moler fino y uniforme; para filtro e italiana basta uno más sencillo.',
        cat: 'grinder',
      },
      {
        q: '¿Cafetera de goteo o filtro manual?',
        a: 'La cafetera de goteo hace una jarra entera con un botón. El filtro manual necesita un hervidor y unos minutos, y te da más control sobre la taza.',
        cat: 'drip',
      },
    ],
  },
  tools: {
    indexTitle: 'Calculadoras de café',
    indexDescription: 'Calculadoras gratuitas para el café en casa, en la oficina y en la cafetería: proporciones, ahorro, coste por taza.',
    groupHome: 'Para casa',
    groupBusiness: 'Para negocios',
    tagHome: 'Casa',
    tagBusiness: 'Negocio',
    open: 'Abrir',
    example: 'Los valores rellenados son ejemplos: cámbialos por los tuyos.',
    currency: 'Moneda',
    result: 'Resultado',
    names: names('Calculadora de proporción café-agua', 'Calculadora de ahorro de una cafetera en casa', 'Calculadora de coste por taza para cafeterías', 'Calculadora del coste del café en la oficina'),
    short: names('Proporción café-agua', 'Ahorro con cafetera en casa', 'Coste por taza en cafetería', 'Coste del café en la oficina'),
    blurbs: names(
      'La cantidad justa de café o de agua para filtro, prensa francesa, espresso y cold brew.',
      '¿Cuánto tarda en amortizarse una cafetera en casa frente al café de la cafetería?',
      'Coste, margen y contribución mensual de cada taza que vendes.',
      'Compara dos soluciones de café para la oficina por mes, por año y por empleado.',
    ),
    outputs: names('gramos de café y agua', 'meses para amortizarla', 'margen por taza', 'coste anual y por persona'),
    next: names(
      '¿Café en casa? Mira en cuánto se amortiza una cafetera',
      '¿Ya tienes la cafetera? Ajusta la dosis justa',
      '¿También sirves a oficinas? Compara el coste del café en la oficina',
      '¿Tienes una cafetería? Calcula tu coste por taza',
    ),
  },
  brewRatio: {
    method: 'Método',
    methods: { filter: 'Filtro', press: 'Prensa francesa', espresso: 'Espresso', coldbrew: 'Cold brew', custom: 'Personalizada' },
    ratio: 'Proporción',
    coffee: 'Café',
    water: 'Agua',
    yield: 'Espresso en la taza',
    inCup: 'En la taza',
    notes: {
      filter: 'Punto de partida basado en el estándar "Golden Cup" de la SCA (unos 55 g de café por litro).',
      press: 'Un punto de partida muy usado: ajústalo a tu gusto.',
      espresso: 'Un punto de partida muy usado (dosis : bebida en la taza): ajústalo a tu gusto.',
      coldbrew: 'Un punto de partida muy usado para un concentrado que se diluye: ajústalo a tu gusto.',
      custom: 'Pon tu propia proporción.',
    },
    result: 'Usa {coffee} g de café para {water} g de agua (proporción 1:{ratio}).',
    resultEspresso: 'Dosis de {coffee} g de café para {water} g de espresso en la taza (proporción 1:{ratio}).',
    hint: '1 g de agua ≈ 1 ml.',
  },
  homePayback: {
    machine: 'Precio de la cafetera',
    beans: 'Café en grano',
    dose: 'Café por bebida',
    extra: 'Otro coste por bebida (leche, etc.)',
    cafe: 'Precio de la misma bebida en la cafetería',
    cups: 'Bebidas al día',
    days: 'Días a la semana',
    maintenance: 'Mantenimiento al año',
    paysIn: 'Se amortiza en',
    homeCost: 'Coste de una bebida en casa',
    saving: 'Ahorro por bebida',
    yearly: 'Ahorro neto al año',
    payback: 'La cafetera se amortiza en',
    never: 'Con estas cifras la cafetera no se amortiza nunca: la bebida cuesta menos, o lo mismo, en la cafetería.',
    daysUnit: 'días',
    monthsUnit: 'meses',
    threeYears: 'Ahorro neto en 3 años',
    atHome: 'En casa',
    out: 'Fuera',
  },
  cafeCost: {
    beans: 'Café en grano',
    dose: 'Café por taza',
    milk: 'Leche por taza',
    milkPrice: 'Precio de la leche',
    packaging: 'Vaso, tapa, azúcar… por taza',
    other: 'Otros costes variables por taza',
    price: 'Precio de venta por taza (con IVA)',
    vat: 'IVA incluido en el precio',
    cupsDay: 'Tazas vendidas al día',
    daysMonth: 'Días de apertura al mes',
    netPrice: 'Precio neto (sin IVA)',
    cost: 'Coste variable por taza',
    margin: 'Margen por taza',
    marginPct: 'Margen sobre el precio neto',
    monthly: 'Contribución mensual (antes de alquiler, personal y otros costes fijos)',
    breakdown: 'A dónde va el precio neto',
    parts: { beans: 'Café', milk: 'Leche', packaging: 'Envase', other: 'Otros', margin: 'Margen' },
    loss: 'Atención: con estas cifras cada taza vendida pierde dinero.',
  },
  officeCost: {
    employees: 'Empleados',
    cupsPerson: 'Cafés por persona al día',
    workdays: 'Días laborables al mes',
    optionA: 'Opción A',
    optionB: 'Opción B',
    optionName: 'Nombre',
    cpc: 'Coste por taza',
    fixed: 'Coste fijo al mes',
    defaultA: 'Cápsulas',
    defaultB: 'Cafetera superautomática',
    cupsMonth: 'Tazas al mes',
    monthly: 'Coste al mes',
    perEmployee: 'Por empleado al mes',
    yearly: 'Coste al año',
    saves: 'Ahorro al año',
    cheaper: '{name} cuesta {diff} menos al año.',
    equal: 'Las dos opciones cuestan lo mismo.',
    breakeven: 'Las dos opciones cuestan lo mismo con unas {cups} tazas al mes.',
    beanHint: 'Para cafeteras de grano: coste por taza = precio por kg × gramos por taza ÷ 1000.',
  },
  guides: { indexDescription: 'Guías prácticas y basadas en datos sobre el café en casa, en la oficina y en la cafetería.' },
};

export const pl = {
  tagline: 'Decyzje o kawie, oparte na danych.',
  nav: { find: 'Znajdź swój ekspres' },
  quiz: {
    title: 'Jaki ekspres do kawy jest dla Ciebie?',
    sub: '3 szybkie pytania: CupVerdict powie Ci, co kupić, i dlaczego.',
    q1: 'Jaką kawę pijesz?',
    a1: { espresso: 'Espresso', milk: 'Cappuccino i z mlekiem', moka: 'Z kawiarki', filter: 'Czarna / przelewowa' },
    q2: 'Ile wysiłku?',
    a2: { button: 'Wystarczy przycisk', ritual: 'Lubię rytuał' },
    q3: 'Twój budżet?',
  },
  verdict: {
    indexDescription: 'Jeden jasny wybór na każdy typ ekspresu, oparty na specyfikacjach publikowanych przez producentów.',
    findMachine: 'Znajdź ekspres dla siebie',
    calc: 'Ile zaoszczędzisz w porównaniu z kawą na mieście?',
    budgetNote: 'Żaden polecany przez nas ekspres tego typu nie mieści się dokładnie w Twoim budżecie: ten jest najbliżej.',
  },
  footer: { line: 'Najpierw liczby. Potem opinie.' },
  about: {
    what: 'ekspresy kapsułkowe, automatyczne i przelewowe, kawiarki, dripy, french pressy i młynki do kawy',
    description: 'O nas: CupVerdict to niezależna strona, która pomaga wybrać ekspres do kawy, kawiarkę albo młynek. Jak wybieramy, skąd są dane i jak zarabiamy.',
  },
  home: {
    metaDescription: 'Darmowe kalkulatory kawowe i poradniki oparte na danych do domu, biura i kawiarni. Każda dana o produkcie ma link do źródła.',
    pickDirect: 'Albo wybierz od razu typ',
    toolsStrip: 'Przydatne kalkulatory: ile naprawdę kosztuje Twoja kawa i ile oszczędzi Ci ekspres.',
    allTools: 'Wszystkie kalkulatory',
    seo: {
      keyphrase: 'CupVerdict',
      title: 'CupVerdict: jaki ekspres do kawy, kawiarkę czy młynek kupić?',
      description: 'CupVerdict pomaga wybrać ekspres kapsułkowy, automatyczny lub przelewowy, kawiarkę, drip albo młynek: 3 pytania, jeden model, dane ze źródłami.',
    },
    how: {
      title: 'Jak wybiera CupVerdict',
      image: 'Rysunek CupVerdict: ekspres kapsułkowy, ekspres kolbowy, kawiarka i młynek do kawy',
      points: [
        {
          t: 'Zaczynasz od tego, jak pijesz kawę',
          d: 'Powiedz, jak pijesz kawę i ile wysiłku chcesz w nią włożyć: najpierw ekspres, który pasuje, z powodem wyjaśnionym prostymi słowami; pod nim wszystkie modele w sprzedaży w Twoim kraju, do posortowania, jak chcesz.',
        },
        {
          t: 'Każda liczba ma źródło',
          d: 'Ciśnienie, pojemność i wymiary pochodzą z oficjalnych stron producentów i z niezależnych testów. Przy każdej wartości jest link, żeby można ją było sprawdzić samodzielnie.',
        },
        {
          t: 'Żadna marka nie płaci za wybór',
          d: 'Jeśli kupisz przez nasz link, możemy dostać prowizję, bez dodatkowych kosztów dla ciebie. Nigdy nie zmienia to wyboru, a żadna marka nie widzi naszych stron przed publikacją.',
        },
      ],
      tests: 'Niezależne testy, które cytujemy:',
      more: 'Jak pracuje CupVerdict, szczegółowo',
    },
    faq: [
      {
        q: 'Kapsułki czy ekspres automatyczny: co wychodzi taniej za filiżankę?',
        a: 'Za filiżankę kawa ziarnista kosztuje mniej niż kapsułki, za to ekspres automatyczny jest droższy w zakupie. Im więcej kawy pijesz, tym szybciej różnica się zwraca.',
        cat: 'superautomatic',
      },
      {
        q: 'Kawiarka czy ekspres do espresso?',
        a: 'Kawiarka robi mocną kawę na kuchence za niewielkie pieniądze, ale nie prawdziwe espresso: parzy przy dużo niższym ciśnieniu. Do espresso z cremą potrzebny jest ekspres ciśnieniowy.',
        cat: 'moka',
      },
      {
        q: 'Czy potrzebuję młynka do kawy?',
        a: 'Tylko jeśli kupujesz kawę ziarnistą: zmielona tuż przed parzeniem zachowuje więcej aromatu. Do espresso młynek musi mielić drobno i równo; do przelewu i kawiarki wystarczy prostszy.',
        cat: 'grinder',
      },
      {
        q: 'Ekspres przelewowy czy drip?',
        a: 'Ekspres przelewowy robi cały dzbanek jednym przyciskiem. Drip wymaga czajnika i kilku minut, ale daje większą kontrolę nad filiżanką.',
        cat: 'drip',
      },
    ],
  },
  tools: {
    indexTitle: 'Kalkulatory kawowe',
    indexDescription: 'Darmowe kalkulatory do kawy w domu, w biurze i w kawiarni: proporcje, oszczędności, koszt filiżanki.',
    groupHome: 'Do domu',
    groupBusiness: 'Dla firm',
    tagHome: 'Dom',
    tagBusiness: 'Firma',
    open: 'Otwórz',
    example: 'Wpisane wartości to przykłady: zastąp je swoimi.',
    currency: 'Waluta',
    result: 'Wynik',
    names: names('Kalkulator proporcji kawy i wody', 'Kalkulator oszczędności z ekspresem w domu', 'Kalkulator kosztu filiżanki w kawiarni', 'Kalkulator kosztów kawy w biurze'),
    short: names('Proporcje kawy i wody', 'Oszczędności z ekspresem', 'Koszt filiżanki w kawiarni', 'Koszt kawy w biurze'),
    blurbs: names(
      'Odpowiednia ilość kawy lub wody do dripa, french pressa, espresso i cold brew.',
      'Po jakim czasie ekspres w domu zwróci się w porównaniu z kawą na mieście?',
      'Koszt, marża i miesięczny wkład każdej sprzedanej filiżanki.',
      'Porównaj dwa sposoby na kawę w biurze: miesięcznie, rocznie i na pracownika.',
    ),
    outputs: names('gramy kawy i wody', 'miesiące do zwrotu', 'marża na filiżance', 'koszt roczny i na osobę'),
    next: names(
      'Kawa w domu? Zobacz, kiedy ekspres się zwróci',
      'Masz już ekspres? Dobierz właściwą dawkę',
      'Obsługujesz też biura? Porównaj koszty kawy w biurze',
      'Prowadzisz kawiarnię? Policz koszt filiżanki',
    ),
  },
  brewRatio: {
    method: 'Metoda',
    methods: { filter: 'Przelew', press: 'French press', espresso: 'Espresso', coldbrew: 'Cold brew', custom: 'Własna' },
    ratio: 'Proporcja',
    coffee: 'Kawa',
    water: 'Woda',
    yield: 'Espresso w filiżance',
    inCup: 'W filiżance',
    notes: {
      filter: 'Punkt wyjścia oparty na standardzie SCA "Golden Cup" (około 55 g kawy na litr).',
      press: 'Często stosowany punkt wyjścia: dostosuj do swojego smaku.',
      espresso: 'Często stosowany punkt wyjścia (dawka : napar w filiżance): dostosuj do smaku.',
      coldbrew: 'Często stosowany punkt wyjścia dla koncentratu do rozcieńczenia: dostosuj do smaku.',
      custom: 'Ustaw własną proporcję.',
    },
    result: 'Użyj {coffee} g kawy na {water} g wody (proporcja 1:{ratio}).',
    resultEspresso: 'Dawka {coffee} g kawy na {water} g espresso w filiżance (proporcja 1:{ratio}).',
    hint: '1 g wody ≈ 1 ml.',
  },
  homePayback: {
    machine: 'Cena ekspresu',
    beans: 'Kawa ziarnista',
    dose: 'Kawa na napój',
    extra: 'Inny koszt na napój (mleko itp.)',
    cafe: 'Cena tego samego napoju w kawiarni',
    cups: 'Napoje dziennie',
    days: 'Dni w tygodniu',
    maintenance: 'Konserwacja rocznie',
    paysIn: 'Zwraca się po',
    homeCost: 'Koszt napoju w domu',
    saving: 'Oszczędność na napoju',
    yearly: 'Oszczędność netto rocznie',
    payback: 'Ekspres zwraca się po',
    never: 'Przy tych liczbach ekspres nigdy się nie zwróci: napój w kawiarni kosztuje mniej albo tyle samo.',
    daysUnit: 'dniach',
    monthsUnit: 'miesiącach',
    threeYears: 'Oszczędność netto w 3 lata',
    atHome: 'W domu',
    out: 'Na mieście',
  },
  cafeCost: {
    beans: 'Kawa ziarnista',
    dose: 'Kawa na filiżankę',
    milk: 'Mleko na filiżankę',
    milkPrice: 'Cena mleka',
    packaging: 'Kubek, wieczko, cukier… na filiżankę',
    other: 'Inne koszty zmienne na filiżankę',
    price: 'Cena sprzedaży filiżanki (z VAT)',
    vat: 'VAT w cenie',
    cupsDay: 'Filiżanki sprzedane dziennie',
    daysMonth: 'Dni otwarcia w miesiącu',
    netPrice: 'Cena netto (bez VAT)',
    cost: 'Koszt zmienny filiżanki',
    margin: 'Marża na filiżance',
    marginPct: 'Marża od ceny netto',
    monthly: 'Miesięczny wkład (przed czynszem, pensjami i innymi kosztami stałymi)',
    breakdown: 'Na co idzie cena netto',
    parts: { beans: 'Kawa', milk: 'Mleko', packaging: 'Opakowanie', other: 'Inne', margin: 'Marża' },
    loss: 'Uwaga: przy tych liczbach każda sprzedana filiżanka przynosi stratę.',
  },
  officeCost: {
    employees: 'Pracownicy',
    cupsPerson: 'Kawy na osobę dziennie',
    workdays: 'Dni robocze w miesiącu',
    optionA: 'Opcja A',
    optionB: 'Opcja B',
    optionName: 'Nazwa',
    cpc: 'Koszt filiżanki',
    fixed: 'Koszt stały miesięcznie',
    defaultA: 'Kapsułki',
    defaultB: 'Ekspres automatyczny',
    cupsMonth: 'Filiżanki miesięcznie',
    monthly: 'Koszt miesięcznie',
    perEmployee: 'Na pracownika miesięcznie',
    yearly: 'Koszt rocznie',
    saves: 'Oszczędność roczna',
    cheaper: '{name} kosztuje rocznie o {diff} mniej.',
    equal: 'Obie opcje kosztują tyle samo.',
    breakeven: 'Obie opcje kosztują tyle samo przy około {cups} filiżankach miesięcznie.',
    beanHint: 'Dla ekspresów na ziarno: koszt filiżanki = cena za kg × gramy na filiżankę ÷ 1000.',
  },
  guides: { indexDescription: 'Praktyczne poradniki oparte na danych o kawie w domu, w biurze i w kawiarni.' },
};

export const sv = {
  tagline: 'Kaffebeslut, uppmätta.',
  nav: { find: 'Hitta din maskin' },
  quiz: {
    title: 'Vilken kaffemaskin passar dig?',
    sub: '3 snabba frågor: CupVerdict säger vilken du ska köpa, och varför.',
    q1: 'Hur dricker du ditt kaffe?',
    a1: { espresso: 'Espresso', milk: 'Cappuccino och med mjölk', moka: 'Mokabryggare', filter: 'Bryggkaffe' },
    q2: 'Hur mycket jobb?',
    a2: { button: 'Trycka på en knapp', ritual: 'Jag gillar ritualen' },
    q3: 'Din budget?',
  },
  verdict: {
    indexDescription: 'Ett tydligt val per typ av kaffemaskin, baserat på tillverkarnas publicerade specifikationer.',
    findMachine: 'Hitta maskinen som passar dig',
    calc: 'Hur mycket sparar du jämfört med att köpa kaffe ute?',
    budgetNote: 'Ingen maskin av den här typen som vi rekommenderar passar exakt i din budget: den här är närmast.',
  },
  footer: { line: 'Siffror först. Åsikter sedan.' },
  about: {
    what: 'kapselmaskiner, helautomater, mokabryggare, kaffebryggare, handbryggare, presskannor och kaffekvarnar',
    description: 'Om oss: CupVerdict är en oberoende sajt som hjälper dig att välja kaffemaskin, mokabryggare eller kaffekvarn. Så väljer vi och så tjänar vi pengar.',
  },
  home: {
    metaDescription: 'Gratis kaffekalkylatorer och databaserade guider för hemmet, kontoret och kaféet. Varje produktuppgift länkar till sin källa.',
    pickDirect: 'Eller välj en typ direkt',
    toolsStrip: 'Praktiska kalkylatorer: vad ditt kaffe egentligen kostar och vad en maskin sparar.',
    allTools: 'Alla kalkylatorer',
    seo: {
      keyphrase: 'CupVerdict',
      title: 'CupVerdict: vilken kaffemaskin, kaffekvarn eller mokabryggare?',
      description: 'CupVerdict hjälper dig att välja kapselmaskin, helautomat, mokabryggare, kaffebryggare, handbryggare eller kaffekvarn: 3 frågor, en modell, med källor.',
    },
    how: {
      title: 'Så väljer CupVerdict',
      image: 'Teckning från CupVerdict: kapselmaskin, espressomaskin, mokabryggare och kaffekvarn',
      points: [
        {
          t: 'Du börjar med hur du dricker kaffet',
          d: 'Berätta hur du dricker ditt kaffe och hur mycket jobb du vill lägga ner: först maskinen som passar, med skälet förklarat med enkla ord; under den alla modeller till salu i ditt land, att sortera som du vill.',
        },
        {
          t: 'Varje siffra har en källa',
          d: 'Tryck, kapacitet och mått kommer från tillverkarnas officiella sidor och från oberoende tester. Bredvid varje uppgift finns en länk så att du kan kontrollera den själv.',
        },
        {
          t: 'Inget märke betalar för att väljas',
          d: 'Köper du via en av våra länkar kan vi få en provision, utan extra kostnad för dig. Det ändrar aldrig valet, och inget märke ser våra sidor innan de publiceras.',
        },
      ],
      tests: 'Oberoende tester vi citerar:',
      more: 'Så arbetar CupVerdict, i detalj',
    },
    faq: [
      {
        q: 'Kapslar eller helautomat: vad kostar minst per kopp?',
        a: 'Per kopp kostar hela bönor mindre än kapslar; helautomaten kostar däremot mer att köpa. Ju mer kaffe du dricker, desto snabbare tjänar du in skillnaden.',
        cat: 'superautomatic',
      },
      {
        q: 'Mokabryggare eller espressomaskin?',
        a: 'Mokabryggaren gör starkt kaffe på spisen för lite pengar, men inte riktig espresso: den brygger med mycket lägre tryck. För espresso med crema behövs en espressomaskin.',
        cat: 'moka',
      },
      {
        q: 'Behöver jag en kaffekvarn?',
        a: 'Bara om du köper hela bönor: nymalet kaffe behåller mer arom. För espresso måste kvarnen mala fint och jämnt; för bryggkaffe och mokabryggare räcker en enklare.',
        cat: 'grinder',
      },
      {
        q: 'Kaffebryggare eller handbryggare?',
        a: 'Kaffebryggaren gör en hel kanna med en knapp. Handbryggaren kräver en vattenkokare och några minuter, och ger mer kontroll över koppen.',
        cat: 'drip',
      },
    ],
  },
  tools: {
    indexTitle: 'Kaffekalkylatorer',
    indexDescription: 'Gratis kalkylatorer för kaffe hemma, på kontoret och på kaféet: proportioner, besparing, kostnad per kopp.',
    groupHome: 'För hemmet',
    groupBusiness: 'För företag',
    tagHome: 'Hemma',
    tagBusiness: 'Företag',
    open: 'Öppna',
    example: 'De ifyllda värdena är exempel: byt ut dem mot dina.',
    currency: 'Valuta',
    result: 'Resultat',
    names: names('Kalkylator för kaffe och vatten', 'Kalkylator för besparing med kaffemaskin hemma', 'Kalkylator för kostnad per kopp på kafé', 'Kalkylator för kaffekostnad på kontoret'),
    short: names('Kaffe och vatten', 'Besparing med maskin hemma', 'Kostnad per kopp på kafé', 'Kaffekostnad på kontoret'),
    blurbs: names(
      'Rätt mängd kaffe eller vatten för bryggkaffe, presskanna, espresso och cold brew.',
      'Hur lång tid tar det innan en kaffemaskin hemma har betalat sig jämfört med att köpa kaffe ute?',
      'Kostnad, marginal och månadsbidrag för varje kopp du säljer.',
      'Jämför två kaffelösningar för kontoret per månad, per år och per anställd.',
    ),
    outputs: names('gram kaffe och vatten', 'månader tills den betalat sig', 'marginal per kopp', 'kostnad per år och person'),
    next: names(
      'Kaffe hemma? Se hur snabbt en maskin betalar sig',
      'Har du redan maskinen? Hitta rätt dos',
      'Levererar du till kontor också? Jämför kontorets kaffekostnad',
      'Driver du ett kafé? Räkna ut din kostnad per kopp',
    ),
  },
  brewRatio: {
    method: 'Metod',
    methods: { filter: 'Bryggkaffe', press: 'Presskanna', espresso: 'Espresso', coldbrew: 'Cold brew', custom: 'Egen' },
    ratio: 'Proportion',
    coffee: 'Kaffe',
    water: 'Vatten',
    yield: 'Espresso i koppen',
    inCup: 'I koppen',
    notes: {
      filter: 'Utgångspunkt enligt SCA:s standard "Golden Cup" (cirka 55 g kaffe per liter).',
      press: 'En vanlig utgångspunkt: justera efter smak.',
      espresso: 'En vanlig utgångspunkt (dos : dryck i koppen): justera efter smak.',
      coldbrew: 'En vanlig utgångspunkt för ett koncentrat att späda: justera efter smak.',
      custom: 'Ställ in din egen proportion.',
    },
    result: 'Använd {coffee} g kaffe till {water} g vatten (proportion 1:{ratio}).',
    resultEspresso: 'Dosera {coffee} g kaffe för {water} g espresso i koppen (proportion 1:{ratio}).',
    hint: '1 g vatten ≈ 1 ml.',
  },
  homePayback: {
    machine: 'Maskinens pris',
    beans: 'Kaffebönor',
    dose: 'Kaffe per dryck',
    extra: 'Annan kostnad per dryck (mjölk m.m.)',
    cafe: 'Pris för samma dryck ute',
    cups: 'Drycker per dag',
    days: 'Dagar per vecka',
    maintenance: 'Underhåll per år',
    paysIn: 'Betalar sig på',
    homeCost: 'Kostnad för en dryck hemma',
    saving: 'Besparing per dryck',
    yearly: 'Nettobesparing per år',
    payback: 'Maskinen betalar sig på',
    never: 'Med de här siffrorna betalar maskinen sig aldrig: drycken kostar mindre, eller lika mycket, ute.',
    daysUnit: 'dagar',
    monthsUnit: 'månader',
    threeYears: 'Nettobesparing på 3 år',
    atHome: 'Hemma',
    out: 'Ute',
  },
  cafeCost: {
    beans: 'Kaffebönor',
    dose: 'Kaffe per kopp',
    milk: 'Mjölk per kopp',
    milkPrice: 'Mjölkpris',
    packaging: 'Mugg, lock, socker… per kopp',
    other: 'Andra rörliga kostnader per kopp',
    price: 'Försäljningspris per kopp (inkl. moms)',
    vat: 'Moms i priset',
    cupsDay: 'Sålda koppar per dag',
    daysMonth: 'Öppetdagar per månad',
    netPrice: 'Nettopris (exkl. moms)',
    cost: 'Rörlig kostnad per kopp',
    margin: 'Marginal per kopp',
    marginPct: 'Marginal på nettopriset',
    monthly: 'Månadsbidrag (före hyra, personal och andra fasta kostnader)',
    breakdown: 'Vart nettopriset går',
    parts: { beans: 'Kaffe', milk: 'Mjölk', packaging: 'Förpackning', other: 'Övrigt', margin: 'Marginal' },
    loss: 'Obs: med de här siffrorna går varje såld kopp med förlust.',
  },
  officeCost: {
    employees: 'Anställda',
    cupsPerson: 'Koppar per person och dag',
    workdays: 'Arbetsdagar per månad',
    optionA: 'Alternativ A',
    optionB: 'Alternativ B',
    optionName: 'Namn',
    cpc: 'Kostnad per kopp',
    fixed: 'Fast kostnad per månad',
    defaultA: 'Kapslar',
    defaultB: 'Helautomatisk maskin',
    cupsMonth: 'Koppar per månad',
    monthly: 'Kostnad per månad',
    perEmployee: 'Per anställd och månad',
    yearly: 'Kostnad per år',
    saves: 'Besparing per år',
    cheaper: '{name} kostar {diff} mindre per år.',
    equal: 'De två alternativen kostar lika mycket.',
    breakeven: 'De två alternativen kostar lika mycket vid cirka {cups} koppar per månad.',
    beanHint: 'För bönmaskiner: kostnad per kopp = pris per kg × gram per kopp ÷ 1000.',
  },
  guides: { indexDescription: 'Praktiska, databaserade guider om kaffe hemma, på kontoret och på kaféet.' },
};
