// CupVerdict copy in every published language. Generic interface text lives in src/i18n/ui.ts;
// what is here overrides it where both define the same key.
import type { PerLang, SiteStrings } from '../../lib/pack';
import { es, pl, sv } from './strings-extra';

type ToolKey = string;

const en = {
  tagline: 'Coffee decisions, measured.',
  skip: 'Skip to content',
  langLabel: 'Language',
  a11y: {
    increase: 'Increase',
    decrease: 'Decrease',
    menu: 'Menu',
    close: 'Close menu',
    mainNav: 'Main navigation',
    showResult: 'Show full result',
  },
  nav: { find: 'Find your machine', verdicts: 'All categories', tools: 'Calculators', guides: 'Guides', about: 'Method' },
  advanced: 'More options',
  quiz: {
    title: 'Which coffee maker is right for you?',
    sub: '3 quick questions: CupVerdict tells you which coffee maker to buy, and why.',
    step: 'Question {n} of 3',
    back: 'Back',
    q1: 'How do you drink your coffee?',
    a1: { espresso: 'Espresso', milk: 'Cappuccino & milk', moka: 'Moka', filter: 'Long / filter' },
    q2: 'How much effort?',
    a2: { button: 'Push a button', ritual: 'I enjoy the ritual' },
    q3: 'Your budget?',
    fallback: 'Or go straight to a type:',
  },
  verdict: {
    indexTitle: 'All categories',
    indexDescription: "One clear pick per type of coffee maker, backed by the manufacturers' published specs.",
    yourVerdict: 'Your verdict',
    ourPick: 'Our top pick',
    picks: 'All our picks',
    goodIf: 'Perfect if',
    skipIf: 'Skip it if',
    criteria: 'What to look at',
    tiers: { low: 'Budget', mid: 'Best balance', high: 'Premium' },
    cta: 'See price on Amazon',
    source: 'Source',
    checked: 'Specs checked on {d} on the manufacturers’ sites.',
    retake: 'Take the test again',
    budgetNote: 'Nothing we recommend of this type fits your budget exactly: this is the closest.',
    calc: 'How much will you save compared with buying coffee out?',
    picksCount: 'Our {n} picks',
    findMachine: 'Find the machine that fits you',
  },
  footer: {
    disclosure:
      'Some links on this site are affiliate links: if you buy through them we may earn a commission, at no extra cost to you. It never changes what we recommend.',
    amazon: 'As an Amazon Associate, CupVerdict earns from qualifying purchases.',
    about: 'About & method',
    privacy: 'Privacy',
    legal: 'Legal notice',
    contact: 'Contact',
    colTools: 'Calculators',
    colSite: 'CupVerdict',
    line: 'Numbers first. Opinions second.',
    publisher: 'A project by',
  },
  about: {
    what: 'capsule, bean-to-cup and espresso machines, moka pots, drip coffee makers, pour-over gear, French presses and coffee grinders',
    description: 'About CupVerdict: an independent site that helps you choose a coffee machine, moka pot or grinder. How we choose, where data comes from, how we earn.',
  },
  home: {
    metaTitle: 'CupVerdict – Coffee calculators and data-driven gear guides',
    metaDescription:
      'Free coffee calculators and data-backed guides for home, office and café. Every product figure links to its source.',
    heroTitle: 'Know what your coffee really costs.',
    heroText:
      'Free calculators and data-backed guides for coffee at home, in the office and in cafés. Every product figure links to its source.',
    calcTitle: 'Your coffee habit',
    calcCups: 'Coffees per day',
    calcPrice: 'Price per coffee',
    calcPerYear: 'a year',
    calcFiveYears: '{v} in five years',
    calcCta: 'How fast would a home machine pay off?',
    calcNote: 'Example values. Change them to yours.',
    sectionTools: 'Calculators',
    sectionMethod: 'How we decide',
    sectionGuides: 'Guides',
    trust: [
      { title: 'Every figure has a source', text: 'Product data comes from manufacturers and is linked, so you can check it yourself.' },
      { title: 'Nothing invented', text: 'No fake tests, no made-up reviews, no invented authors.' },
      { title: 'Free, no sign-up', text: 'Every calculator works instantly, in your browser.' },
    ],
    method: [
      { title: 'From the spec sheet', text: 'We start from published specifications, not from marketing claims.' },
      { title: 'Criteria you can see', text: 'Each comparison explains what matters and why, so you can decide for yourself.' },
      { title: 'Kept current', text: 'When a product changes or disappears, the page changes too.' },
    ],
    methodHeading: 'We compare on data, not on hype.',
    pickDirect: 'Or pick a type directly',
    toolsStrip: 'Handy calculators: what your coffee really costs, and what a machine saves you.',
    methodLink: 'Read our method',
    allTools: 'All calculators',
    seo: {
      keyphrase: 'CupVerdict',
      title: 'CupVerdict: which coffee machine, grinder or moka pot to buy',
      description: 'CupVerdict helps you choose a capsule, bean-to-cup or espresso machine, moka pot, drip maker or grinder: 3 questions, one model, with sources.',
    },
    how: {
      title: 'How CupVerdict chooses',
      image: 'Capsule machine, espresso machine, moka pot and coffee grinder: some of the coffee gear CupVerdict compares (drawing)',
      points: [
        {
          t: 'Start from how you drink it',
          d: 'Tell us how you drink your coffee and how much effort you want to put in: first the machine that fits, with the reason in plain words; below it, every model on sale in your country, to sort as you like.',
        },
        {
          t: 'Every figure has a source',
          d: 'Pressure, capacity and size come from the manufacturers’ official pages and from independent tests. Next to each figure there is a link so you can check it yourself.',
        },
        {
          t: 'No brand pays to be picked',
          d: 'If you buy through one of our links we may earn a commission, at no extra cost to you. It never changes the pick, and no brand sees our pages before they go live.',
        },
      ],
      tests: 'Independent tests we quote:',
      more: 'How CupVerdict works, in detail',
    },
    faq: [
      {
        q: 'Capsules or bean-to-cup: which costs less per cup?',
        a: 'Per cup, whole beans cost less than capsules; the bean-to-cup machine costs more to buy. The more coffee you drink, the sooner the difference pays back.',
        cat: 'superautomatic',
      },
      {
        q: 'Moka pot or espresso machine?',
        a: 'A moka pot makes strong coffee on the hob for little money, but not true espresso: it brews at far lower pressure. For espresso with crema you need an espresso machine.',
        cat: 'moka',
      },
      {
        q: 'Do I need a coffee grinder?',
        a: 'Only if you buy whole beans: coffee ground just before brewing keeps more aroma. For espresso the grinder must grind fine and even; for filter and moka a simpler one is enough.',
        cat: 'grinder',
      },
      {
        q: 'Drip coffee maker or pour-over?',
        a: 'The drip machine makes a full jug at the push of a button. Pour-over needs a kettle and a few minutes of your time, and gives you more control over the cup.',
        cat: 'drip',
      },
    ],
  },
  tools: {
    indexTitle: 'Coffee calculators',
    indexDescription:
      'Free calculators for coffee at home, in the office and in cafés: ratios, savings, cost per cup.',
    groupHome: 'For home',
    groupBusiness: 'For business',
    tagHome: 'Home',
    tagBusiness: 'Business',
    open: 'Open',
    example: 'The values filled in are examples: replace them with yours.',
    currency: 'Currency',
    result: 'Result',
    names: {
      'tool-brew-ratio': 'Coffee-to-water ratio calculator',
      'tool-home-payback': 'Home coffee machine savings calculator',
      'tool-cafe-cost': 'Café cost-per-cup calculator',
      'tool-office-cost': 'Office coffee cost calculator',
    } as Record<ToolKey, string>,
    short: {
      'tool-brew-ratio': 'Coffee-to-water ratio',
      'tool-home-payback': 'Home machine savings',
      'tool-cafe-cost': 'Café cost per cup',
      'tool-office-cost': 'Office coffee cost',
    } as Record<ToolKey, string>,
    blurbs: {
      'tool-brew-ratio': 'The right amount of coffee or water for filter, French press, espresso and cold brew.',
      'tool-home-payback': 'How long until a home machine pays for itself compared with buying coffee out?',
      'tool-cafe-cost': 'Cost, margin and monthly contribution of every cup you sell.',
      'tool-office-cost': 'Compare two office coffee solutions per month, per year and per employee.',
    } as Record<ToolKey, string>,
    outputs: {
      'tool-brew-ratio': 'grams of coffee and water',
      'tool-home-payback': 'months to pay back',
      'tool-cafe-cost': 'margin per cup',
      'tool-office-cost': 'cost per year and per person',
    } as Record<ToolKey, string>,
    next: {
      'tool-brew-ratio': 'Making coffee at home? See how fast a machine pays for itself',
      'tool-home-payback': 'Got the machine? Dial in the right dose',
      'tool-cafe-cost': 'Supplying offices too? Compare office coffee costs',
      'tool-office-cost': 'Running a café? Work out your cost per cup',
    } as Record<ToolKey, string>,
  },
  brewRatio: {
    method: 'Method',
    methods: {
      filter: 'Filter',
      press: 'French press',
      espresso: 'Espresso',
      coldbrew: 'Cold brew',
      custom: 'Custom',
    },
    ratio: 'Ratio',
    coffee: 'Coffee',
    water: 'Water',
    yield: 'Espresso in the cup',
    inCup: 'In the cup',
    notes: {
      filter: 'Starting point based on the SCA "Golden Cup" standard (about 55 g of coffee per litre).',
      press: 'A widely used starting point: adjust to taste.',
      espresso: 'A widely used starting point (dose : liquid in the cup): adjust to taste.',
      coldbrew: 'A widely used starting point for a concentrate to dilute: adjust to taste.',
      custom: 'Set your own ratio.',
    },
    result: 'Use {coffee} g of coffee for {water} g of water (ratio 1:{ratio}).',
    resultEspresso: 'Dose {coffee} g of coffee for {water} g of espresso in the cup (ratio 1:{ratio}).',
    hint: '1 g of water ≈ 1 ml.',
  },
  homePayback: {
    machine: 'Machine price',
    beans: 'Coffee beans',
    dose: 'Coffee per drink',
    extra: 'Other cost per drink (milk, etc.)',
    cafe: 'Price of the same drink out',
    cups: 'Drinks per day',
    days: 'Days per week',
    maintenance: 'Maintenance per year',
    paysIn: 'Pays for itself in',
    homeCost: 'Cost of a drink at home',
    saving: 'Saving per drink',
    yearly: 'Net saving per year',
    payback: 'The machine pays for itself in',
    never:
      'With these numbers the machine never pays for itself: the drink costs less when you buy it out, or about the same.',
    daysUnit: 'days',
    monthsUnit: 'months',
    threeYears: 'Net saving over 3 years',
    atHome: 'At home',
    out: 'Out',
  },
  cafeCost: {
    beans: 'Coffee beans',
    dose: 'Coffee per cup',
    milk: 'Milk per cup',
    milkPrice: 'Milk price',
    packaging: 'Cup, lid, sugar… per cup',
    other: 'Other variable costs per cup',
    price: 'Selling price per cup (incl. tax)',
    vat: 'VAT / sales tax in the price',
    cupsDay: 'Cups sold per day',
    daysMonth: 'Opening days per month',
    netPrice: 'Net price (excl. tax)',
    cost: 'Variable cost per cup',
    margin: 'Margin per cup',
    marginPct: 'Margin on net price',
    monthly: 'Monthly contribution (before rent, staff and other fixed costs)',
    breakdown: 'Where the net price goes',
    parts: { beans: 'Coffee', milk: 'Milk', packaging: 'Packaging', other: 'Other', margin: 'Margin' },
    loss: 'Warning: with these numbers every cup sold loses money.',
  },
  officeCost: {
    employees: 'Employees',
    cupsPerson: 'Coffees per person per day',
    workdays: 'Working days per month',
    optionA: 'Option A',
    optionB: 'Option B',
    optionName: 'Name',
    cpc: 'Cost per cup',
    fixed: 'Fixed cost per month',
    defaultA: 'Capsules',
    defaultB: 'Bean-to-cup machine',
    cupsMonth: 'Cups per month',
    monthly: 'Cost per month',
    perEmployee: 'Per employee per month',
    yearly: 'Cost per year',
    saves: 'Yearly saving',
    cheaper: '{name} costs {diff} less per year.',
    equal: 'The two options cost the same.',
    breakeven: 'The two options cost the same at about {cups} cups per month.',
    beanHint: 'For bean machines: cost per cup = price per kg × grams per cup ÷ 1000.',
  },
  guides: {
    indexTitle: 'Guides',
    indexDescription: 'Practical, data-driven guides to coffee at home, in the office and in cafés.',
    empty: 'New guides are on the way.',
    updated: 'Updated',
    related: 'Related guides',
  },
  notFound: {
    title: 'Page not found',
    text: 'This page does not exist (any more).',
    back: 'Go to the homepage',
  },
};

export type CupStrings = typeof en;

const it: CupStrings = {
  tagline: 'Le scelte sul caffè, misurate.',
  skip: 'Vai al contenuto',
  langLabel: 'Lingua',
  a11y: {
    increase: 'Aumenta',
    decrease: 'Diminuisci',
    menu: 'Menu',
    close: 'Chiudi il menu',
    mainNav: 'Navigazione principale',
    showResult: 'Vedi il risultato completo',
  },
  nav: { find: 'Trova la tua macchina', verdicts: 'Tutte le categorie', tools: 'Calcolatori', guides: 'Guide', about: 'Metodo' },
  advanced: 'Altre opzioni',
  quiz: {
    title: 'Quale macchina da caffè fa per te?',
    sub: '3 domande veloci: CupVerdict ti dice quale comprare, e perché.',
    step: 'Domanda {n} di 3',
    back: 'Indietro',
    q1: 'Come bevi il caffè?',
    a1: { espresso: 'Espresso', milk: 'Cappuccino e latte', moka: 'Moka', filter: 'Lungo / americano' },
    q2: 'Quanto vuoi impegnarti?',
    a2: { button: 'Premo un pulsante', ritual: 'Mi piace il rituale' },
    q3: 'Quanto vuoi spendere?',
    fallback: 'Oppure vai direttamente a un tipo:',
  },
  verdict: {
    indexTitle: 'Tutte le categorie',
    indexDescription: 'Una scelta chiara per ogni tipo di macchina da caffè, basata sulle specifiche pubblicate dai produttori.',
    yourVerdict: 'Il tuo verdetto',
    ourPick: 'La nostra scelta',
    picks: 'Tutte le nostre scelte',
    goodIf: 'Perfetta se',
    skipIf: 'Lasciala perdere se',
    criteria: 'Cosa guardare',
    tiers: { low: 'Economica', mid: 'Equilibrata', high: 'Top di gamma' },
    cta: 'Vedi prezzo su Amazon',
    source: 'Fonte',
    checked: 'Specifiche verificate il {d} sui siti dei produttori.',
    retake: 'Rifai il test',
    budgetNote: 'In questa categoria non abbiamo una scelta che stia esattamente nel tuo budget: questa è la più vicina.',
    calc: 'Quanto risparmi rispetto al caffè al bar?',
    picksCount: 'Le nostre {n} scelte',
    findMachine: 'Trova la macchina che fa per te',
  },
  footer: {
    disclosure:
      'Alcuni link di questo sito sono link di affiliazione: se acquisti tramite questi link potremmo ricevere una commissione, senza costi aggiuntivi per te. Non cambia mai ciò che consigliamo.',
    amazon: 'In qualità di Affiliato Amazon, CupVerdict riceve un guadagno dagli acquisti idonei.',
    about: 'Chi siamo e metodo',
    privacy: 'Privacy',
    legal: 'Note legali',
    contact: 'Contatti',
    colTools: 'Calcolatori',
    colSite: 'CupVerdict',
    line: 'Prima i numeri. Poi le opinioni.',
    publisher: 'Un progetto di',
  },
  about: {
    what: 'macchine da caffè a capsule, automatiche e manuali, moka, macchine per caffè filtro, filtri manuali e macinacaffè',
    description: 'Chi siamo: CupVerdict è un sito indipendente che ti aiuta a scegliere macchina da caffè, moka o macinacaffè. Come scegliamo e come guadagniamo.',
  },
  home: {
    metaTitle: 'CupVerdict – Calcolatori per il caffè e guide basate sui dati',
    metaDescription:
      'Calcolatori gratuiti e guide basate sui dati per il caffè a casa, in ufficio e al bar. Ogni dato sui prodotti rimanda alla sua fonte.',
    heroTitle: 'Scopri quanto ti costa davvero il caffè.',
    heroText:
      'Calcolatori gratuiti e guide basate sui dati per il caffè a casa, in ufficio e al bar. Ogni dato sui prodotti rimanda alla sua fonte.',
    calcTitle: 'Il tuo caffè di ogni giorno',
    calcCups: 'Caffè al giorno',
    calcPrice: 'Prezzo di un caffè',
    calcPerYear: "all'anno",
    calcFiveYears: '{v} in cinque anni',
    calcCta: 'In quanto si ripagherebbe una macchina a casa?',
    calcNote: 'Valori di esempio: cambiali con i tuoi.',
    sectionTools: 'Calcolatori',
    sectionMethod: 'Come decidiamo',
    sectionGuides: 'Guide',
    trust: [
      { title: 'Ogni dato ha una fonte', text: 'I dati dei prodotti vengono dai produttori e sono collegati alla fonte, così puoi controllarli.' },
      { title: 'Niente di inventato', text: 'Nessun test finto, nessuna recensione inventata, nessun autore inventato.' },
      { title: 'Gratis, senza registrazione', text: 'Ogni calcolatore funziona subito, nel tuo browser.' },
    ],
    method: [
      { title: 'Dalla scheda tecnica', text: 'Partiamo dalle specifiche pubblicate, non dagli slogan pubblicitari.' },
      { title: 'Criteri visibili', text: 'Ogni confronto spiega cosa conta e perché, così puoi decidere tu.' },
      { title: 'Sempre aggiornati', text: 'Quando un prodotto cambia o sparisce, cambia anche la pagina.' },
    ],
    methodHeading: 'Confrontiamo i dati, non la pubblicità.',
    pickDirect: 'Oppure scegli direttamente il tipo',
    toolsStrip: 'Calcolatori utili: quanto ti costa davvero il caffè e quanto risparmi con una macchina.',
    methodLink: 'Il nostro metodo',
    allTools: 'Tutti i calcolatori',
    seo: {
      keyphrase: 'CupVerdict',
      title: 'CupVerdict: quale macchina da caffè o macinacaffè comprare',
      description: 'CupVerdict ti aiuta a scegliere macchina a capsule, automatica o manuale, moka, caffè filtro o macinacaffè: 3 domande, un modello, con le fonti.',
    },
    how: {
      title: 'Come sceglie CupVerdict',
      image: 'Macchina a capsule, macchina da espresso, moka e macinacaffè: alcuni dei prodotti che CupVerdict confronta (disegno)',
      points: [
        {
          t: 'Parti da come bevi il caffè',
          d: 'Dicci come bevi il caffè e quanta fatica vuoi fare: prima la macchina adatta, con il motivo in parole semplici; sotto, tutti i modelli in vendita nel tuo paese, da ordinare come vuoi.',
        },
        {
          t: 'Ogni numero ha la sua fonte',
          d: 'Pressione, capacità e dimensioni vengono dalle pagine ufficiali dei produttori e dai test indipendenti. Accanto a ogni dato c’è il link per controllarlo da te.',
        },
        {
          t: 'Nessuno paga per essere scelto',
          d: 'Se compri da un nostro link potremmo ricevere una commissione, senza costi per te. Non cambia mai la scelta, e nessun marchio vede le nostre pagine prima che escano.',
        },
      ],
      tests: 'Test indipendenti che citiamo:',
      more: 'Come lavora CupVerdict, nel dettaglio',
    },
    faq: [
      {
        q: 'Capsule o macchina automatica: quale costa meno a tazzina?',
        a: 'A tazzina il caffè in chicchi costa meno delle capsule; la macchina automatica però costa di più all’acquisto. Più caffè bevi, prima la differenza si ripaga.',
        cat: 'superautomatic',
      },
      {
        q: 'Moka o macchina da espresso?',
        a: 'La moka fa un caffè forte sul fornello con poca spesa, ma non un vero espresso: estrae a una pressione molto più bassa. Per l’espresso con la crema serve una macchina da espresso.',
        cat: 'moka',
      },
      {
        q: 'Mi serve un macinacaffè?',
        a: 'Solo se compri il caffè in chicchi: macinato appena prima conserva più aroma. Per l’espresso serve un macinacaffè che macini fine e regolare; per filtro e moka ne basta uno più semplice.',
        cat: 'grinder',
      },
      {
        q: 'Macchina per caffè filtro o filtro manuale?',
        a: 'La macchina fa una caraffa intera premendo un pulsante. Il filtro manuale chiede un bollitore e qualche minuto, e ti dà più controllo sulla tazza.',
        cat: 'drip',
      },
    ],
  },
  tools: {
    indexTitle: 'Calcolatori per il caffè',
    indexDescription:
      'Calcolatori gratuiti per il caffè a casa, in ufficio e al bar: dosi, risparmio, costo per tazzina.',
    groupHome: 'Per la casa',
    groupBusiness: 'Per le aziende',
    tagHome: 'Casa',
    tagBusiness: 'Aziende',
    open: 'Apri',
    example: 'I valori inseriti sono esempi: sostituiscili con i tuoi.',
    currency: 'Valuta',
    result: 'Risultato',
    names: {
      'tool-brew-ratio': 'Calcolatore dosi caffè e acqua',
      'tool-home-payback': 'Calcolatore risparmio macchina da caffè',
      'tool-cafe-cost': 'Calcolatore costo per tazzina (bar)',
      'tool-office-cost': 'Calcolatore costo del caffè in ufficio',
    },
    short: {
      'tool-brew-ratio': 'Dosi caffè e acqua',
      'tool-home-payback': 'Risparmio macchina a casa',
      'tool-cafe-cost': 'Costo per tazzina',
      'tool-office-cost': 'Caffè in ufficio',
    },
    blurbs: {
      'tool-brew-ratio': 'La quantità giusta di caffè o di acqua per filtro, french press, espresso e cold brew.',
      'tool-home-payback': 'In quanto tempo una macchina a casa si ripaga rispetto al caffè al bar?',
      'tool-cafe-cost': 'Costo, margine e guadagno mensile di ogni tazzina che vendi.',
      'tool-office-cost': "Confronta due soluzioni per il caffè in ufficio: al mese, all'anno e per dipendente.",
    },
    outputs: {
      'tool-brew-ratio': 'grammi di caffè e di acqua',
      'tool-home-payback': 'mesi per ripagarla',
      'tool-cafe-cost': 'margine per tazza',
      'tool-office-cost': "costo all'anno e a persona",
    },
    next: {
      'tool-brew-ratio': 'Fai il caffè a casa? Scopri in quanto si ripaga una macchina',
      'tool-home-payback': 'Hai la macchina? Trova la dose giusta',
      'tool-cafe-cost': 'Servi anche uffici? Confronta i costi del caffè in ufficio',
      'tool-office-cost': 'Gestisci un bar? Calcola il costo per tazzina',
    },
  },
  brewRatio: {
    method: 'Metodo',
    methods: {
      filter: 'Filtro',
      press: 'French press',
      espresso: 'Espresso',
      coldbrew: 'Cold brew',
      custom: 'Libero',
    },
    ratio: 'Rapporto',
    coffee: 'Caffè',
    water: 'Acqua',
    yield: 'Espresso in tazza',
    inCup: 'In tazza',
    notes: {
      filter: 'Punto di partenza basato sullo standard "Golden Cup" della SCA (circa 55 g di caffè per litro).',
      press: 'Un punto di partenza molto diffuso: regolalo a gusto.',
      espresso: 'Un punto di partenza molto diffuso (dose : liquido in tazza): regolalo a gusto.',
      coldbrew: 'Un punto di partenza molto diffuso per un concentrato da diluire: regolalo a gusto.',
      custom: 'Imposta il tuo rapporto.',
    },
    result: 'Usa {coffee} g di caffè per {water} g di acqua (rapporto 1:{ratio}).',
    resultEspresso: 'Usa {coffee} g di caffè per ottenere {water} g di espresso in tazza (rapporto 1:{ratio}).',
    hint: '1 g di acqua ≈ 1 ml.',
  },
  homePayback: {
    machine: 'Prezzo della macchina',
    beans: 'Caffè in grani',
    dose: 'Caffè per bevanda',
    extra: 'Altri costi per bevanda (latte, ecc.)',
    cafe: 'Prezzo della stessa bevanda al bar',
    cups: 'Bevande al giorno',
    days: 'Giorni alla settimana',
    maintenance: "Manutenzione all'anno",
    paysIn: 'Si ripaga in',
    homeCost: 'Costo di una bevanda fatta in casa',
    saving: 'Risparmio per bevanda',
    yearly: "Risparmio netto all'anno",
    payback: 'La macchina si ripaga in',
    never:
      'Con questi numeri la macchina non si ripaga mai: al bar la bevanda costa meno che farla in casa, o circa uguale.',
    daysUnit: 'giorni',
    monthsUnit: 'mesi',
    threeYears: 'Risparmio netto in 3 anni',
    atHome: 'A casa',
    out: 'Al bar',
  },
  cafeCost: {
    beans: 'Caffè in grani',
    dose: 'Caffè per tazzina',
    milk: 'Latte per tazza',
    milkPrice: 'Prezzo del latte',
    packaging: 'Bicchiere, coperchio, zucchero… per tazza',
    other: 'Altri costi variabili per tazza',
    price: 'Prezzo di vendita per tazza (IVA inclusa)',
    vat: 'IVA inclusa nel prezzo',
    cupsDay: 'Tazze vendute al giorno',
    daysMonth: 'Giorni di apertura al mese',
    netPrice: 'Prezzo netto (senza IVA)',
    cost: 'Costo variabile per tazza',
    margin: 'Margine per tazza',
    marginPct: 'Margine sul prezzo netto',
    monthly: 'Margine mensile (prima di affitto, personale e altri costi fissi)',
    breakdown: 'Dove va il prezzo netto',
    parts: { beans: 'Caffè', milk: 'Latte', packaging: 'Confezione', other: 'Altro', margin: 'Margine' },
    loss: 'Attenzione: con questi numeri ogni tazza venduta è in perdita.',
  },
  officeCost: {
    employees: 'Dipendenti',
    cupsPerson: 'Caffè a persona al giorno',
    workdays: 'Giorni lavorativi al mese',
    optionA: 'Opzione A',
    optionB: 'Opzione B',
    optionName: 'Nome',
    cpc: 'Costo per tazza',
    fixed: 'Costo fisso al mese',
    defaultA: 'Capsule',
    defaultB: 'Macchina a grani',
    cupsMonth: 'Tazze al mese',
    monthly: 'Costo al mese',
    perEmployee: 'Per dipendente al mese',
    yearly: "Costo all'anno",
    saves: "Risparmio all'anno",
    cheaper: "{name} costa {diff} in meno all'anno.",
    equal: 'Le due opzioni costano uguale.',
    breakeven: 'Le due opzioni costano uguale a circa {cups} tazze al mese.',
    beanHint: 'Per le macchine a grani: costo per tazza = prezzo al kg × grammi per tazza ÷ 1000.',
  },
  guides: {
    indexTitle: 'Guide',
    indexDescription: 'Guide pratiche e basate sui dati sul caffè a casa, in ufficio e al bar.',
    empty: 'Nuove guide in arrivo.',
    updated: 'Aggiornato',
    related: 'Guide correlate',
  },
  notFound: {
    title: 'Pagina non trovata',
    text: 'Questa pagina non esiste (più).',
    back: 'Vai alla home',
  },
};

const de: CupStrings = {
  tagline: 'Kaffee-Entscheidungen, gemessen.',
  skip: 'Zum Inhalt springen',
  langLabel: 'Sprache',
  a11y: {
    increase: 'Erhöhen',
    decrease: 'Verringern',
    menu: 'Menü',
    close: 'Menü schließen',
    mainNav: 'Hauptnavigation',
    showResult: 'Ganzes Ergebnis anzeigen',
  },
  nav: { find: 'Finde deine Maschine', verdicts: 'Alle Kategorien', tools: 'Rechner', guides: 'Ratgeber', about: 'Methode' },
  advanced: 'Weitere Optionen',
  quiz: {
    title: 'Welche Kaffeemaschine passt zu dir?',
    sub: '3 schnelle Fragen: CupVerdict sagt dir, welche du kaufen solltest, und warum.',
    step: 'Frage {n} von 3',
    back: 'Zurück',
    q1: 'Wie trinkst du deinen Kaffee?',
    a1: { espresso: 'Espresso', milk: 'Cappuccino & Milch', moka: 'Moka', filter: 'Filterkaffee' },
    q2: 'Wie viel Aufwand?',
    a2: { button: 'Knopfdruck', ritual: 'Ich mag das Ritual' },
    q3: 'Dein Budget?',
    fallback: 'Oder direkt zu einem Typ:',
  },
  verdict: {
    indexTitle: 'Alle Kategorien',
    indexDescription: 'Eine klare Empfehlung pro Maschinentyp, gestützt auf die veröffentlichten Herstellerangaben.',
    yourVerdict: 'Dein Urteil',
    ourPick: 'Unsere Wahl',
    picks: 'Alle Empfehlungen',
    goodIf: 'Perfekt, wenn',
    skipIf: 'Lass es, wenn',
    criteria: 'Worauf du achten solltest',
    tiers: { low: 'Günstig', mid: 'Beste Balance', high: 'Premium' },
    cta: 'Preis auf Amazon ansehen',
    source: 'Quelle',
    checked: 'Daten am {d} auf den Herstellerseiten geprüft.',
    retake: 'Test wiederholen',
    budgetNote: 'In dieser Kategorie empfehlen wir nichts genau in deinem Budget: Das ist die nächstliegende Wahl.',
    calc: 'Wie viel sparst du gegenüber Kaffee unterwegs?',
    picksCount: 'Unsere {n} Empfehlungen',
    findMachine: 'Finde die Maschine, die zu dir passt',
  },
  footer: {
    disclosure:
      'Einige Links auf dieser Website sind Affiliate-Links: Wenn du darüber kaufst, erhalten wir möglicherweise eine Provision, ohne Mehrkosten für dich. Das ändert nie, was wir empfehlen.',
    amazon: 'Als Amazon-Partner verdient CupVerdict an qualifizierten Verkäufen.',
    about: 'Über uns & Methode',
    privacy: 'Datenschutz',
    legal: 'Impressum',
    contact: 'Kontakt',
    colTools: 'Rechner',
    colSite: 'CupVerdict',
    line: 'Erst die Zahlen. Dann die Meinung.',
    publisher: 'Ein Projekt von',
  },
  about: {
    what: 'Kapselmaschinen, Kaffeevollautomaten, Siebträger, Espressokocher, Filterkaffeemaschinen, Handfilter und Kaffeemühlen',
    description: 'Über uns: CupVerdict ist eine unabhängige Seite, die dir hilft, Kaffeemaschine, Espressokocher oder Mühle zu wählen. Wie wir auswählen und verdienen.',
  },
  home: {
    metaTitle: 'CupVerdict – Kaffee-Rechner und datenbasierte Ratgeber',
    metaDescription:
      'Kostenlose Kaffee-Rechner und datenbasierte Ratgeber für zu Hause, Büro und Café. Jede Produktangabe verweist auf ihre Quelle.',
    heroTitle: 'Finde heraus, was dein Kaffee wirklich kostet.',
    heroText:
      'Kostenlose Rechner und datenbasierte Ratgeber für Kaffee zu Hause, im Büro und im Café. Jede Produktangabe verweist auf ihre Quelle.',
    calcTitle: 'Deine Kaffeegewohnheit',
    calcCups: 'Kaffees pro Tag',
    calcPrice: 'Preis pro Kaffee',
    calcPerYear: 'pro Jahr',
    calcFiveYears: '{v} in fünf Jahren',
    calcCta: 'Wann würde sich eine Maschine zu Hause bezahlt machen?',
    calcNote: 'Beispielwerte. Ersetze sie durch deine.',
    sectionTools: 'Rechner',
    sectionMethod: 'Wie wir entscheiden',
    sectionGuides: 'Ratgeber',
    trust: [
      { title: 'Jede Zahl hat eine Quelle', text: 'Produktdaten stammen von den Herstellern und sind verlinkt, damit du sie selbst prüfen kannst.' },
      { title: 'Nichts erfunden', text: 'Keine erfundenen Tests, keine ausgedachten Bewertungen, keine erfundenen Autoren.' },
      { title: 'Kostenlos, ohne Anmeldung', text: 'Jeder Rechner funktioniert sofort in deinem Browser.' },
    ],
    method: [
      { title: 'Aus dem Datenblatt', text: 'Wir gehen von veröffentlichten technischen Daten aus, nicht von Werbeversprechen.' },
      { title: 'Sichtbare Kriterien', text: 'Jeder Vergleich erklärt, worauf es ankommt und warum, damit du selbst entscheiden kannst.' },
      { title: 'Immer aktuell', text: 'Ändert sich ein Produkt oder verschwindet es, ändert sich auch die Seite.' },
    ],
    methodHeading: 'Wir vergleichen Daten, keine Werbeversprechen.',
    pickDirect: 'Oder wähle direkt einen Typ',
    toolsStrip: 'Praktische Rechner: was dein Kaffee wirklich kostet und was eine Maschine spart.',
    methodLink: 'Unsere Methode',
    allTools: 'Alle Rechner',
    seo: {
      keyphrase: 'CupVerdict',
      title: 'CupVerdict: Welche Kaffeemaschine oder Kaffeemühle kaufen?',
      description: 'CupVerdict hilft bei der Wahl von Kapselmaschine, Vollautomat, Siebträger, Espressokocher, Filtermaschine oder Mühle: 3 Fragen, ein Modell, mit Quellen.',
    },
    how: {
      title: 'So wählt CupVerdict aus',
      image: 'Kapselmaschine, Siebträgermaschine, Espressokocher und Kaffeemühle: einige der Geräte, die CupVerdict vergleicht (Zeichnung)',
      points: [
        {
          t: 'Du startest bei deinem Kaffee',
          d: 'Sag uns, wie du deinen Kaffee trinkst und wie viel Aufwand du willst: zuerst die passende Maschine, mit dem Grund in einfachen Worten; darunter alle Modelle, die in deinem Land zu kaufen sind, sortierbar wie du willst.',
        },
        {
          t: 'Jede Zahl hat ihre Quelle',
          d: 'Druck, Füllmenge und Maße stammen von den offiziellen Herstellerseiten und aus unabhängigen Tests. Neben jedem Wert steht der Link, damit du ihn selbst prüfen kannst.',
        },
        {
          t: 'Keine Marke zahlt für die Auswahl',
          d: 'Kaufst du über einen unserer Links, bekommen wir vielleicht eine Provision, ohne Mehrkosten für dich. An der Auswahl ändert das nie etwas, und keine Marke sieht unsere Seiten vorab.',
        },
      ],
      tests: 'Unabhängige Tests, die wir zitieren:',
      more: 'So arbeitet CupVerdict, im Detail',
    },
    faq: [
      {
        q: 'Kapseln oder Vollautomat: was kostet pro Tasse weniger?',
        a: 'Pro Tasse sind ganze Bohnen günstiger als Kapseln; dafür kostet der Vollautomat mehr in der Anschaffung. Je mehr Kaffee du trinkst, desto schneller rechnet sich der Unterschied.',
        cat: 'superautomatic',
      },
      {
        q: 'Espressokocher oder Siebträgermaschine?',
        a: 'Der Espressokocher macht kräftigen Kaffee auf dem Herd für wenig Geld, aber keinen echten Espresso: Er brüht mit viel weniger Druck. Für Espresso mit Crema brauchst du eine Siebträgermaschine.',
        cat: 'moka',
      },
      {
        q: 'Brauche ich eine Kaffeemühle?',
        a: 'Nur wenn du ganze Bohnen kaufst: frisch gemahlen bleibt mehr Aroma. Für Espresso muss die Mühle fein und gleichmäßig mahlen; für Filter und Espressokocher reicht eine einfachere.',
        cat: 'grinder',
      },
      {
        q: 'Filterkaffeemaschine oder Handfilter?',
        a: 'Die Maschine macht eine ganze Kanne auf Knopfdruck. Der Handfilter braucht einen Wasserkocher und ein paar Minuten, und du hast mehr Kontrolle über die Tasse.',
        cat: 'drip',
      },
    ],
  },
  tools: {
    indexTitle: 'Kaffee-Rechner',
    indexDescription:
      'Kostenlose Rechner für Kaffee zu Hause, im Büro und im Café: Verhältnis, Ersparnis, Kosten pro Tasse.',
    groupHome: 'Für zu Hause',
    groupBusiness: 'Fürs Geschäft',
    tagHome: 'Zu Hause',
    tagBusiness: 'Business',
    open: 'Öffnen',
    example: 'Die eingetragenen Werte sind Beispiele: Ersetze sie durch deine eigenen.',
    currency: 'Währung',
    result: 'Ergebnis',
    names: {
      'tool-brew-ratio': 'Kaffee-Wasser-Verhältnis-Rechner',
      'tool-home-payback': 'Rechner: Lohnt sich eine Kaffeemaschine?',
      'tool-cafe-cost': 'Kosten-pro-Tasse-Rechner fürs Café',
      'tool-office-cost': 'Kaffeekosten-Rechner fürs Büro',
    },
    short: {
      'tool-brew-ratio': 'Kaffee-Wasser-Verhältnis',
      'tool-home-payback': 'Ersparnis mit eigener Maschine',
      'tool-cafe-cost': 'Kosten pro Tasse im Café',
      'tool-office-cost': 'Kaffeekosten im Büro',
    },
    blurbs: {
      'tool-brew-ratio': 'Die richtige Menge Kaffee oder Wasser für Filterkaffee, French Press, Espresso und Cold Brew.',
      'tool-home-payback': 'Wann hat sich eine Maschine für zu Hause im Vergleich zum Kaffee unterwegs bezahlt gemacht?',
      'tool-cafe-cost': 'Kosten, Marge und monatlicher Deckungsbeitrag jeder verkauften Tasse.',
      'tool-office-cost': 'Zwei Kaffeelösungen fürs Büro vergleichen: pro Monat, pro Jahr und pro Person.',
    },
    outputs: {
      'tool-brew-ratio': 'Gramm Kaffee und Wasser',
      'tool-home-payback': 'Monate bis zur Amortisation',
      'tool-cafe-cost': 'Marge pro Tasse',
      'tool-office-cost': 'Kosten pro Jahr und Person',
    },
    next: {
      'tool-brew-ratio': 'Kaffee zu Hause? Sieh nach, wann sich eine Maschine bezahlt macht',
      'tool-home-payback': 'Maschine schon da? Finde die richtige Dosis',
      'tool-cafe-cost': 'Belieferst du auch Büros? Vergleiche die Kaffeekosten im Büro',
      'tool-office-cost': 'Du führst ein Café? Berechne die Kosten pro Tasse',
    },
  },
  brewRatio: {
    method: 'Zubereitung',
    methods: {
      filter: 'Filter',
      press: 'French Press',
      espresso: 'Espresso',
      coldbrew: 'Cold Brew',
      custom: 'Eigenes',
    },
    ratio: 'Verhältnis',
    coffee: 'Kaffee',
    water: 'Wasser',
    yield: 'Espresso in der Tasse',
    inCup: 'In der Tasse',
    notes: {
      filter: 'Ausgangswert nach dem „Golden Cup“-Standard der SCA (etwa 55 g Kaffee pro Liter).',
      press: 'Ein verbreiteter Ausgangswert: nach Geschmack anpassen.',
      espresso: 'Ein verbreiteter Ausgangswert (Kaffeemenge : Flüssigkeit in der Tasse): nach Geschmack anpassen.',
      coldbrew: 'Ein verbreiteter Ausgangswert für ein Konzentrat zum Verdünnen: nach Geschmack anpassen.',
      custom: 'Lege dein eigenes Verhältnis fest.',
    },
    result: 'Nimm {coffee} g Kaffee für {water} g Wasser (Verhältnis 1:{ratio}).',
    resultEspresso: 'Nimm {coffee} g Kaffee für {water} g Espresso in der Tasse (Verhältnis 1:{ratio}).',
    hint: '1 g Wasser ≈ 1 ml.',
  },
  homePayback: {
    machine: 'Preis der Maschine',
    beans: 'Kaffeebohnen',
    dose: 'Kaffee pro Getränk',
    extra: 'Weitere Kosten pro Getränk (Milch usw.)',
    cafe: 'Preis desselben Getränks unterwegs',
    cups: 'Getränke pro Tag',
    days: 'Tage pro Woche',
    maintenance: 'Wartung pro Jahr',
    paysIn: 'Bezahlt gemacht nach',
    homeCost: 'Kosten eines Getränks zu Hause',
    saving: 'Ersparnis pro Getränk',
    yearly: 'Nettoersparnis pro Jahr',
    payback: 'Die Maschine hat sich bezahlt gemacht nach',
    never:
      'Mit diesen Zahlen macht sich die Maschine nie bezahlt: Unterwegs kostet das Getränk weniger als zu Hause oder etwa gleich viel.',
    daysUnit: 'Tagen',
    monthsUnit: 'Monaten',
    threeYears: 'Nettoersparnis über 3 Jahre',
    atHome: 'Zu Hause',
    out: 'Unterwegs',
  },
  cafeCost: {
    beans: 'Kaffeebohnen',
    dose: 'Kaffee pro Tasse',
    milk: 'Milch pro Tasse',
    milkPrice: 'Milchpreis',
    packaging: 'Becher, Deckel, Zucker … pro Tasse',
    other: 'Weitere variable Kosten pro Tasse',
    price: 'Verkaufspreis pro Tasse (inkl. MwSt.)',
    vat: 'Im Preis enthaltene MwSt.',
    cupsDay: 'Verkaufte Tassen pro Tag',
    daysMonth: 'Öffnungstage pro Monat',
    netPrice: 'Nettopreis (ohne MwSt.)',
    cost: 'Variable Kosten pro Tasse',
    margin: 'Marge pro Tasse',
    marginPct: 'Marge am Nettopreis',
    monthly: 'Monatlicher Deckungsbeitrag (vor Miete, Personal und anderen Fixkosten)',
    breakdown: 'Wohin der Nettopreis geht',
    parts: { beans: 'Kaffee', milk: 'Milch', packaging: 'Verpackung', other: 'Sonstiges', margin: 'Marge' },
    loss: 'Achtung: Mit diesen Zahlen verliert jede verkaufte Tasse Geld.',
  },
  officeCost: {
    employees: 'Mitarbeitende',
    cupsPerson: 'Kaffees pro Person und Tag',
    workdays: 'Arbeitstage pro Monat',
    optionA: 'Option A',
    optionB: 'Option B',
    optionName: 'Bezeichnung',
    cpc: 'Kosten pro Tasse',
    fixed: 'Fixkosten pro Monat',
    defaultA: 'Kapseln',
    defaultB: 'Kaffeevollautomat',
    cupsMonth: 'Tassen pro Monat',
    monthly: 'Kosten pro Monat',
    perEmployee: 'Pro Person und Monat',
    yearly: 'Kosten pro Jahr',
    saves: 'Ersparnis pro Jahr',
    cheaper: '{name} kostet {diff} weniger pro Jahr.',
    equal: 'Beide Optionen kosten gleich viel.',
    breakeven: 'Bei etwa {cups} Tassen pro Monat kosten beide Optionen gleich viel.',
    beanHint: 'Für Bohnenmaschinen: Kosten pro Tasse = Preis pro kg × Gramm pro Tasse ÷ 1000.',
  },
  guides: {
    indexTitle: 'Ratgeber',
    indexDescription: 'Praktische, datenbasierte Ratgeber rund um Kaffee zu Hause, im Büro und im Café.',
    empty: 'Neue Ratgeber sind in Arbeit.',
    updated: 'Aktualisiert',
    related: 'Passende Ratgeber',
  },
  notFound: {
    title: 'Seite nicht gefunden',
    text: 'Diese Seite gibt es nicht (mehr).',
    back: 'Zur Startseite',
  },
};

// Spanish, Polish and Swedish carry only the site's own copy (strings-extra.ts): the generic
// interface text comes from the engine.
type Cup = typeof en;
type CupExtra = Omit<Cup, 'skip' | 'langLabel' | 'a11y' | 'advanced' | 'notFound' | 'nav' | 'quiz' | 'verdict' | 'footer' | 'home' | 'guides'> & {
  nav: Pick<Cup['nav'], 'find'>;
  quiz: Pick<Cup['quiz'], 'title' | 'sub' | 'q1' | 'a1' | 'q2' | 'a2' | 'q3'>;
  verdict: Pick<Cup['verdict'], 'indexDescription' | 'findMachine' | 'calc' | 'budgetNote'>;
  footer: Pick<Cup['footer'], 'line'>;
  home: Pick<Cup['home'], 'metaDescription' | 'pickDirect' | 'toolsStrip' | 'allTools' | 'seo' | 'how' | 'faq'>;
  guides: Pick<Cup['guides'], 'indexDescription'>;
};
const extra: Record<'es' | 'pl' | 'sv', SiteStrings & CupExtra> = { es, pl, sv };

export const strings = { en, it, de, ...extra } satisfies PerLang<SiteStrings & (CupStrings | CupExtra)>;
